In [1]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to C:\Users\Tafheem
[nltk_data]     Ahemad\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Tafheem
[nltk_data]     Ahemad\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Tafheem
[nltk_data]     Ahemad\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [2]:
import pandas as pd
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))


mails=pd.read_csv('Datasets/spam classification/SMSSpamCollection.txt',
				sep="	",names=["name","messages"])

In [3]:
mails

name                                           messages
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk import WordNetLemmatizer
from nltk.corpus import stopwords

In [5]:
lemmatizer=WordNetLemmatizer()
all_common_Words=stopwords.words('english')

In [6]:
corpus=[]

for sen in mails['messages']:
	sen=sen[:]
	sen=sen.lower()
	sen=word_tokenize(sen)
	sen=[lemmatizer.lemmatize(word) for word in sen if word not in all_common_Words]
	sen=" ".join(sen)
	corpus.append(sen)


In [7]:
corpus

['go jurong point , crazy .. available bugis n great world la e buffet ... cine got amore wat ...',
 'ok lar ... joking wif u oni ...',
 "free entry 2 wkly comp win fa cup final tkts 21st may 2005. text fa 87121 receive entry question ( std txt rate ) & c 's apply 08452810075over18 's",
 'u dun say early hor ... u c already say ...',
 "nah n't think go usf , life around though",
 "freemsg hey darling 's 3 week 's word back ! 'd like fun still ? tb ok ! xxx std chgs send , £1.50 rcv",
 'even brother like speak . treat like aid patent .',
 "per request 'melle melle ( oru minnaminunginte nurungu vettam ) ' set callertune caller . press * 9 copy friend callertune",
 'winner ! ! valued network customer selected receivea £900 prize reward ! claim call 09061701461. claim code kl341 . valid 12 hour .',
 'mobile 11 month ? u r entitled update latest colour mobile camera free ! call mobile update co free 08002986030',
 "'m gon na home soon n't want talk stuff anymore tonight , k ? 've cried enou

##### min_df --> all vocabulary with count < min_dif will removed
##### max_df --> all vocabulary with count > max_dif will removed (may be spam)

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
CV=CountVectorizer(max_features=100,binary=True,min_df=0.005)

In [9]:
# Not list of word , make a sentence and pass it
X=CV.fit_transform(corpus).toarray()

CV.vocabulary_

{'go': 19,
 'great': 23,
 'got': 22,
 'wat': 89,
 'ok': 56,
 'free': 15,
 'win': 93,
 'text': 76,
 'txt': 83,
 'say': 67,
 'already': 0,
 'think': 79,
 'hey': 26,
 'week': 91,
 'back': 3,
 'like': 35,
 'still': 72,
 'send': 69,
 'friend': 16,
 'prize': 61,
 'claim': 7,
 'call': 4,
 'mobile': 46,
 'co': 8,
 'na': 50,
 'home': 28,
 'want': 88,
 've': 86,
 'today': 81,
 'cash': 6,
 'day': 11,
 'reply': 64,
 'www': 96,
 'right': 65,
 'take': 74,
 'time': 80,
 'message': 43,
 'oh': 55,
 'yes': 99,
 'make': 41,
 'way': 90,
 'dont': 13,
 'miss': 45,
 'ur': 85,
 'going': 20,
 'da': 10,
 'lor': 38,
 'meet': 42,
 'really': 63,
 'know': 31,
 'lol': 37,
 'love': 39,
 're': 62,
 'll': 36,
 'let': 34,
 'work': 94,
 'yeah': 97,
 'tell': 75,
 'thanks': 77,
 'uk': 84,
 'please': 59,
 'msg': 48,
 'see': 68,
 'pls': 60,
 'need': 51,
 'tomorrow': 82,
 'hope': 29,
 'well': 92,
 'lt': 40,
 'gt': 24,
 'get': 17,
 'ask': 1,
 'morning': 47,
 'happy': 25,
 'sorry': 71,
 'give': 18,
 'new': 52,
 'find': 14,
 'ye

In [10]:

X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0

In [17]:
# N-Gram
from sklearn.feature_extraction.text import CountVectorizer
CV=CountVectorizer(max_features=50,ngram_range=(1,2))

In [18]:
X=CV.fit_transform(corpus).toarray()

CV.vocabulary_

{'go': 9,
 'got': 12,
 'ok': 29,
 'free': 7,
 'text': 42,
 'txt': 46,
 'think': 43,
 'week': 49,
 'back': 0,
 'like': 18,
 'still': 38,
 'send': 36,
 'call': 1,
 'mobile': 25,
 'co': 2,
 'home': 15,
 'want': 48,
 'today': 45,
 'day': 5,
 'reply': 34,
 'take': 40,
 'time': 44,
 'make': 24,
 'dont': 6,
 'ur': 47,
 'going': 10,
 'da': 4,
 'lor': 20,
 'know': 16,
 'love': 21,
 'll': 19,
 'tell': 41,
 'please': 32,
 'msg': 26,
 'see': 35,
 'pls': 33,
 'need': 27,
 'lt': 22,
 'gt': 13,
 'lt gt': 23,
 'get': 8,
 'sorry': 37,
 'new': 28,
 'later': 17,
 'good': 11,
 'come': 3,
 'hi': 14,
 'stop': 39,
 'one': 30,
 'phone': 31}

In [19]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [49]:
Y=mails['name']

from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [52]:
Y=encoder.fit_transform(mails['name'])
Y

array([0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0])

In [56]:
Y.shape

(5572,)

In [57]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=.25,random_state=42)

In [58]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()

model.fit(X_train,Y_train)

MultinomialNB()

In [59]:
Y_pred=model.predict(X_test)

In [60]:
from sklearn.metrics import classification_report,accuracy_score

print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.94      0.98      0.96      1207
           1       0.81      0.59      0.68       186

    accuracy                           0.93      1393
   macro avg       0.87      0.78      0.82      1393
weighted avg       0.92      0.93      0.92      1393



In [61]:
print(accuracy_score(Y_test,Y_pred))

0.9267767408470926
