In [1]:
import pandas as pd
import numpy as np
import re
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))


mails=pd.read_csv('Datasets/spam classification/SMSSpamCollection.txt',
				sep="	",names=["name","messages"])

In [2]:
mails

name                                           messages
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk import WordNetLemmatizer
from nltk.corpus import stopwords

In [4]:
lemmatizer=WordNetLemmatizer()
all_common_Words=stopwords.words('english')

In [5]:
corpus=[]

for sen in mails['messages']:
	sen=sen[:]
	sen=re.sub('[^a-z A-z]','',sen)
	sen=sen.lower()
	sen=word_tokenize(sen)
	sen=[lemmatizer.lemmatize(word) for word in sen if word not in all_common_Words]
	sen=" ".join(sen)
	corpus.append(sen)


In [6]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry questionstd txt ratetcs apply over',
 'u dun say early hor u c already say',
 'nah dont think go usf life around though',
 'freemsg hey darling week word back id like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'im gon na home soon dont want talk stuff anymore tonight k ive cried enough today',
 'six chance win cash pound txt csh send cost pday day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim tc wwwdbukn

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfIdf=TfidfVectorizer(max_features=100)

In [8]:
X=tfIdf.fit_transform(corpus).toarray()

tfIdf.vocabulary_

{'go': 22,
 'great': 26,
 'got': 25,
 'wat': 90,
 'ok': 59,
 'free': 18,
 'win': 94,
 'text': 78,
 'txt': 86,
 'say': 69,
 'already': 0,
 'dont': 16,
 'think': 82,
 'life': 39,
 'hey': 28,
 'week': 92,
 'back': 5,
 'like': 40,
 'still': 74,
 'send': 71,
 'friend': 19,
 'prize': 64,
 'claim': 9,
 'call': 6,
 'mobile': 49,
 'co': 10,
 'im': 33,
 'na': 53,
 'home': 30,
 'want': 89,
 'ive': 34,
 'today': 84,
 'cash': 8,
 'day': 13,
 'reply': 66,
 'right': 67,
 'take': 76,
 'time': 83,
 'message': 46,
 'oh': 58,
 'yes': 99,
 'make': 44,
 'thats': 80,
 'way': 91,
 'miss': 48,
 'ur': 87,
 'going': 23,
 'da': 12,
 'lor': 41,
 'meet': 45,
 'really': 65,
 'know': 35,
 'love': 42,
 'amp': 1,
 'ill': 32,
 'let': 38,
 'work': 95,
 'yeah': 97,
 'tell': 77,
 'anything': 2,
 'thanks': 79,
 'please': 62,
 'msg': 51,
 'see': 70,
 'pls': 63,
 'need': 54,
 'tomorrow': 85,
 'hope': 31,
 'well': 93,
 'ltgt': 43,
 'didnt': 15,
 'get': 20,
 'cant': 7,
 'ask': 3,
 'morning': 50,
 'happy': 27,
 'sorry': 73,
 'g

In [9]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.433, 0, 0, 0.453, 0.544, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.558, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.453, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0.469, 0, 0, 0, 0, 0, 0, 0, 0.495, 0, 0, 0, 0, 0, 0, 0, 0.574, 0, 0, 0, 0, 0],
       [0.465, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.445, 0, 0, 0, 0, 0, 0.434, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.512, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [10]:
# N-Gram
tfIdf=TfidfVectorizer(max_features=50,ngram_range=(1,2))

In [11]:
X=tfIdf.fit_transform(corpus).toarray()

tfIdf.vocabulary_

{'go': 9,
 'got': 12,
 'ok': 28,
 'free': 7,
 'text': 41,
 'txt': 45,
 'say': 33,
 'dont': 6,
 'think': 42,
 'week': 48,
 'back': 0,
 'like': 19,
 'still': 37,
 'send': 35,
 'call': 1,
 'mobile': 24,
 'im': 16,
 'home': 14,
 'want': 47,
 'today': 44,
 'day': 5,
 'reply': 32,
 'take': 39,
 'time': 43,
 'make': 23,
 'ur': 46,
 'going': 10,
 'da': 4,
 'lor': 20,
 'know': 17,
 'love': 21,
 'ill': 15,
 'tell': 40,
 'please': 31,
 'see': 34,
 'need': 25,
 'well': 49,
 'ltgt': 22,
 'get': 8,
 'cant': 2,
 'sorry': 36,
 'new': 26,
 'later': 18,
 'good': 11,
 'come': 3,
 'hi': 13,
 'stop': 38,
 'one': 29,
 'night': 27,
 'phone': 30}

In [12]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0.69, 0, 0, 0.723, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0.554, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.573, 0, 0, 0, 0.604, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0.553, 0, 0, 0.539, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.635, 0, 0, 0, 0, 0, 0, 0],
       [0.425, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.384, 0, 0, 0, 0, 0, 0, 0, 0, 0.369, 0, 0, 0, 0, 0, 0, 0.403, 0, 0.422, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.

In [13]:
Y=mails['name']

from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [14]:
Y=encoder.fit_transform(mails['name'])
Y

array([0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0])

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=.25,random_state=42)

In [16]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()

model.fit(X_train,Y_train)

MultinomialNB()

In [17]:
Y_pred=model.predict(X_test)

In [18]:
from sklearn.metrics import classification_report,accuracy_score

print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.95      0.98      0.96      1207
           1       0.85      0.64      0.73       186

    accuracy                           0.94      1393
   macro avg       0.90      0.81      0.85      1393
weighted avg       0.93      0.94      0.93      1393



In [19]:
print(accuracy_score(Y_test,Y_pred))

0.9368269921033741
